name: Build CI

on:
  push:
    branches:
      - main
      - 'testing/**'
      - 'feature/**'
      - 'hotfix/**'
    # Run pipeline for release tags
    tags:
      - 'v*.*.*'

jobs:
  build-java:
    runs-on: [ubuntu-24.04]

    steps:
      # Set up
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11

      # Build normal JAR
      - name: Build with Maven
        run: mvn -f release-to-issue-java/pom.xml --batch-mode --update-snapshots package
      - name: Upload plugin artifacts
        uses: actions/upload-artifact@v5
        with:
          name: release-to-issue.jar
          path: release-to-issue-java/target/release-to-issue-java-*.jar

      # Build executable JAR
      - name: Build executable JAR with Maven
        run: mvn -f release-to-issue-java/pom.xml clean compile assembly:single
      - name: Upload plugin artifacts
        uses: actions/upload-artifact@v5
        with:
          name: release-to-issue-jar-with-dependencies.jar
          path: release-to-issue-java/target/release-to-issue-java-*-jar-with-dependencies.jar

  build-docker:
    runs-on: [ubuntu-24.04]
    needs: [build-java]

    steps:
      # Set up
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: maxkratz/release-to-issue
          platforms: linux/amd64,linux/arm64
